### ISSUE TITLE
failed to load device tree

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [szclsya/x13s-alarm#3]
Excuse this maybe stupid question: When using `linux-x13s` from this repo, I'm having trouble loading the device tree at boot time.

The device tree, the Kernel and the initramfs are located on the ESP in my case. Apart from my device specific parameters, my cmdline consists of:

> dtb=/sc8280xp-lenovo-thinkpad-x13s.dtb efi=novamap audit=0

I'm using Grub from alarm upstream as bootloader.

Interestingly, I can boot any x13s patched alarm USB, but I don't reach at booting my installed Linux from disk.

Have you got any hints on required parameters to be added to the cmdline?

**Comment by szclsya** [comment]
Hi.
I'm also using GRUB2 and here's my config:

```
menuentry "Arch Linux ARM" {
  devicetree /boot/sc8280xp-lenovo-thinkpad-x13s.dtb
  linux /boot/Image root=PARTUUID=REDACTED rw efi=novamap,noruntime clk_ignore_unused pd_ignore_unused rootwait loglevel=1
  initrd /boot/initramfs-linux.img
}
```
In theory specifying dtb in kernel cmdline should also work (other users of this repo have tried systemd-boot with dtb in cmdline and it works), so I'm not sure what's wrong. Probably for GRUB you need to add `/boot/` as a prefix for the dtb path?

**Comment by TheOneWithTheBraid** [comment]
Ah, thanks for the information. Seems like it was a combination of a broken kernel (compiled myself) and the devicetree which should better be placed into GRUB's  devicetree command rather than into the command line.

And nope, the path is correct: Using root disk and boot disk encryption. Relative to what grub sees during boot time, the path is /dtbs/... hence.
